// Generated by CoffeeScript 1.8.0
(function() {
  var BashyOS,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BashyOS = (function() {
    function BashyOS(bashy_sprite) {
      this.bashy_sprite = bashy_sprite;
      this.handleTerminalInput = __bind(this.handleTerminalInput, this);
    }

    BashyOS.prototype.handleTerminalInput = function(input) {
      this.bashy_sprite.moveRight();
      return "> " + input + "\n" + input;
    };

    return BashyOS;

  })();

  window.BashyOS = BashyOS;

}).call(this);
