// Generated by CoffeeScript 1.8.0
(function() {
  var BashySprite;

  BashySprite = (function() {
    function BashySprite(sprite) {
      this.sprite = sprite;
    }

    BashySprite.prototype.moveLeft = function() {
      if (this.sprite.x > 0) {
        return this.sprite.x -= 48;
      }
    };

    BashySprite.prototype.moveRight = function() {
      var limit;
      limit = 288 - this.sprite.getBounds().width;
      if (this.sprite.x < limit) {
        return this.sprite.x += 48;
      }
    };

    BashySprite.prototype.moveUp = function() {
      if (this.sprite.y > 0) {
        return this.sprite.y -= 48;
      }
    };

    BashySprite.prototype.moveDown = function() {
      var limit;
      limit = 288 - this.sprite.getBounds().height;
      if (this.sprite.y < limit) {
        return this.sprite.y += 48;
      }
    };

    return BashySprite;

  })();

  this.BashyOS = (function() {
    function BashyOS() {}

    return BashyOS;

  })();

  this.FileSystem = (function() {
    function FileSystem() {}

    return FileSystem;

  })();

  jQuery(function() {
    var bashy_himself, canvas, stage, startGame, tick;
    canvas = $("#bashy_canvas")[0];
    stage = new createjs.Stage(canvas);
    bashy_himself = new Image();
    bashy_himself.onload = function() {
      return startGame();
    };
    bashy_himself.src = "assets/bashy_sprite_sheet.png";
    tick = function() {
      return stage.update();
    };
    return startGame = function() {
      var bashySpriteSheet, bashy_sprite, os, sprite;
      bashySpriteSheet = new createjs.SpriteSheet({
        images: [bashy_himself],
        frames: {
          width: 64,
          height: 64
        },
        animations: {
          walking: [0, 4, "walking"]
        }
      });
      sprite = new createjs.Sprite(bashySpriteSheet, 0);
      sprite.gotoAndPlay("walking");
      sprite.currentFrame = 0;
      stage.addChild(sprite);
      bashy_sprite = new BashySprite(sprite);
      createjs.Ticker.addEventListener("tick", tick);
      createjs.Ticker.useRAF = true;
      createjs.Ticker.setFPS(5);
      os = new BashyOS(bashy_sprite);
      return $('#terminal').terminal(os.handleTerminalInput, {
        greetings: "",
        prompt: '> ',
        name: 'test'
      });
    };
  });

}).call(this);
